name: Tests
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
on: [repository_dispatch, workflow_dispatch]
jobs:
  build:
    name: Run Python Tests
    # SAWRA >> USE_MATRIX
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        # SAWRA >> USE_MATRIX
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          make install
          make test-requirements
      - name: Test with pytest
        run: |
          set -o pipefail
          make test-ci | tee pytest-coverage.txt

      # SAWRA >> NEEDS_ACTION
      # - name: Pytest coverage comment
      #   continue-on-error: true # Workflows running on a fork can't post comments
      #   uses: MishaKav/pytest-coverage-comment@main
      #   if: github.event_name == 'pull_request'
      #   with:
      #     pytest-coverage-path: ./pytest-coverage.txt
      #     junitxml-path: ./pytest.xml